from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    import PIL.Image


class RawPrinter(Protocol):
    """What PeripageClient needs from the underlying printer object —
    matches peripage.Printer's public surface. Lets tests inject a fake
    without installing peripage/PyBluez."""

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def isConnected(self) -> bool: ...
    def reset(self) -> None: ...
    def setConcentration(self, concentration: int, wait: bool = False) -> None: ...
    def printBreak(self, size: int = 0x40) -> None: ...
    def printImage(self, img: PIL.Image.Image, delay: float = 0.01) -> None: ...
    def getDeviceBattery(self) -> int: ...
    def getRowBytes(self) -> int: ...
    def tellPrinter(self, byteseq: bytes) -> None: ...
